### ISSUE TITLE
Add option to ec2-pod role to add managed hosts to the inventory by IP address instead of hostname.

### ISSUE THREAD

**Issue by opadron** [Kitware/gobig#39]
We should have the ec2-pod role add managed instances to the running inventory by their IP addresses rather than hostnames.  Their hostnames tend to be long enough to cause problems.

See the comments for the `control_path` option in your default global `/etc/ansible/ansible.cfg` file for details.

This change should also be made the new default.

**Comment by opadron** [comment]
Here's the relevant section:

```
# The path to use for the ControlPath sockets. This defaults to
# "%(directory)s/ansible-ssh-%%h-%%p-%%r", however on some systems with
# very long hostnames or very long path names (caused by long user names or
# deeply nested home directories) this can exceed the character limit on
# file socket names (108 characters for most platforms). In that case, you
# may wish to shorten the string below.
#
# Example:
# control_path = %(directory)s/%%h-%%r
#control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r
```

**Comment by zachmullen** [comment]
Just ran into this yesterday in COVALIC, I put the fix directly into the repo so others wouldn't encounter it: https://github.com/girder/covalic/pull/136

**Comment by zachmullen** [comment]
And by yesterday I mean 3 days ago... man, I'm losing it!

**Comment by opadron** [comment]
Yeah, for some reason, I can't seem to get the `control_path` change to stick, so I'm running a temporary hack to reference my ec2 instances by IP -- so just sidestepping the problem.

Soon, I hope to clean that up and put in a PR.
