### ISSUE TITLE
Current install of mongodb is 2.4.9,  girder requires 2.6+

### ISSUE THREAD

**Issue by kotfic** [Kitware/gobig#42]
Currently the mongodb role installs the default mongodb from ubuntu repositories (https://github.com/Kitware/gobig/blob/master/roles/mongodb-install/tasks/main.yml#L3-L11),  this does not support full text search and is not sufficient for supporting girder. Girder requires 2.6+  and default ubuntu version is 2.4.9.

Girder mostly works but throws the following errors when searching for users, groups,  or using the 'text' field of most of the restful endpoints:

```
500 Internal Server Error {"message": "OperationFailure: OperationFailure(u\"command SON([('count', u'group'), ('query', {'$text': {'$search': u'a'}})]) on namespace girder.$cmd failed: exception: invalid operator: $search\",)"
```

**Comment by opadron** [comment]
Fixed by #43
